name: ${name}
author: plushmonkey
version: ${version}
main: com.plushnode.atlacore.AtlaCorePlugin
softdepend: [Factions, GriefPrevention, LWC, Towny, WorldGuard]
commands:
  atla:
    usage: /<command>
