name: ${name}
author: plushmonkey
version: ${version}
main: com.plushnode.atlacore.AtlaCorePlugin
softdepend: [ProjectKorra, Factions, GriefPrevention, LWC, Towny, WorldGuard]
api-version: 1.13
commands:
  atla:
    aliases: []
    usage: /<command>
permissions:
  atla.admin:
    default: op
    children:
      atla.player: true
      atla.command.reload: true
      atla.command.add: true
      atla.command.modify: true
  atla.player:
    default: true
    children:
      atla.command.bind: true
      atla.command.choose: true
      atla.command.display: true
      atla.command.help: true
      atla.command.preset: true
      atla.board.display: true
      atla.air: true
      atla.chi: true
      atla.earth: true
      atla.fire: true
      atla.water: true
  atla.air:
    children:
      atla.command.choose.Air: true
      atla.ability.AirAgility: true
      atla.ability.AirBlast: true
      atla.ability.AirBurst: true
      atla.ability.AirScooter: true
      atla.ability.AirShield: true
      atla.ability.AirSpout: true
      atla.ability.AirStream: true
      atla.ability.AirSuction: true
      atla.ability.AirSweep: true
      atla.ability.AirSwipe: true
      atla.ability.GracefulDescent: true
      atla.ability.Suffocate: true
      atla.ability.Tornado: true
      atla.ability.Twister: true
  atla.earth:
    children:
      atla.command.choose.Earth: true
      atla.ability.Catapult: true
      atla.ability.Collapse: true
      atla.ability.EarthBlast: true
      atla.ability.EarthSmash: true
      atla.ability.Shockwave: true
      atla.ability.DensityShift: true
  atla.fire:
    children:
      atla.command.choose.Fire: true
      atla.ability.Blaze: true
      atla.ability.Combustion: true
      atla.ability.FireBlast: true
      atla.ability.FireBlastCharged: true
      atla.ability.FireBurst: true
      atla.ability.FireJet: true
      atla.ability.FireShield: true
      atla.ability.HeatControl: true
      atla.ability.Lightning: true
      atla.ability.WallOfFire: true
      atla.ability.FireKick: true
      atla.ability.FireSpin: true
      atla.ability.FireWheel: true
      atla.ability.JetBlast: true
      atla.ability.JetBlaze: true
